create table public.recurring_items (
                                      id bigint generated by default as identity not null,
                                      created_at timestamp with time zone not null default now(),
                                      last_bought date null,
                                      name text not null,
                                      created_by uuid not null,
                                      frequency integer not null,
                                      frequency_type text null,
                                      constraint recurring_items_pkey primary key (id),
                                      constraint recurring_items_created_by_fkey foreign KEY (created_by) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;
