create table public.list_items (
                                 id bigint generated by default as identity not null,
                                 created_at timestamp with time zone not null default now(),
                                 recurring_item_id bigint null,
                                 name text not null,
                                 user_id uuid not null,
                                 quantity integer not null default 1,
                                 constraint list_items_pkey primary key (id),
                                 constraint list_items_recurring_item_id_fkey foreign KEY (recurring_item_id) references recurring_items (id),
                                 constraint list_items_user_id_fkey foreign KEY (user_id) references auth.users (id),
                                 constraint list_items_user_id_fkey1 foreign KEY (user_id) references user_profile (user_id)
) TABLESPACE pg_default;
