-- Create shopping_lists table
create table public.shopping_lists (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  is_default boolean not null default false,
  constraint shopping_lists_pkey primary key (id)
) TABLESPACE pg_default;

-- Add list_id column to list_items
alter table public.list_items
  add column if not exists list_id bigint;

-- Add foreign key constraint to list_items
alter table public.list_items
  add constraint list_items_list_id_fkey foreign key (list_id) references shopping_lists (id) on delete cascade;

-- Enable RLS
alter table public.shopping_lists enable row level security;

-- Policies for shopping_lists
create policy "Enable all for everyone" on public.shopping_lists
  as permissive for all to public using (true) with check (true);
